name: Release and Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set TAG_NAME
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # TODO: Add Docker login step here
      # Hint: Use the docker/login-action@v3
      # Use the secrets you created: REGISTRY_USER and REGISTRY_TOKEN

      # TODO: Add Docker build and push step here
      # Hint: Use docker/build-push-action@v5
      # Set context to current directory
      # Push to: docker.io/${{ secrets.REGISTRY_USER }}/example-application:${{ env.TAG_NAME }}

  trigger-deployment-update:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Set TAG_NAME again
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Trigger workflow in env repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update-deployment.yaml
          repo: yousifalassaly/example-environment
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: main
          inputs: |
            {
              "tag_name": "${{ env.TAG_NAME }}",
              "image": "docker.io/${{ secrets.REGISTRY_USER }}/example-application"
            }